config:
  RANDOM_SEED : 1111
  NUM_AREA : 100                         # number of meeting zone (2 persons can be enter is this zone)
  TIMEMEET : 5                        # minutes staying in the meeting zone
  SIM_TIME : 200                     # Simulation time in minutes (in on cycle)
  NUM_PERSON : 100                   # number of person in the simulation
  CAPACITY_AREA : 100                 # number of object (person) go in meeting zone (in one cycle)
  NUM_DAY : 10               # number of cycle
  PROBA_CONTAMINATION : 0.97           # probability to infect someone
  MAX_NEIGHBOURS : 20
  PROBA_HEAL : 0.3
  PROBA_DEATH : 0.3
  TIME_WITHOUT_S : 2
  TIME_CONTAMINATED : 7
  TIME_TOO_MUCH : 15

#  liste_dead = []
#  proba_meet = 0.5
#  malus_conta = 8  # Malus si personne conta divise la proba de meeting
#  stats = {"healthful": [nombre_pers-1], "cont_without_s": [1], "contaminated": [0], "cured": [0], "dead": [0]}
